version: '2'
services:
  mongodb:
    image : mongo:4.0.2
    container_name: mongodb
    environment :
      - 'MONGO_DATA_DIR=/data/db'
      - 'MONGO_LOG_DIR=/dev/null'
      - 'MONGODB_USER=gauss' 
      - 'MONGODB_PASS=gauss'
    volumes:
      - './.data/mongodb:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles  
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    links:
      - 'mongodb'
    ports:
      - '8082:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=default'
      - 'ME_CONFIG_BASICAUTH_USERNAME=gauss'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=gauss'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
    restart: always
